### ISSUE TITLE
Hubot help system improvements

### ISSUE THREAD

**Issue by joeyguerra** [hubot-new/hubot#11]
Original issue
https://github.com/hubotio/hubot/issues/1490

from @arigoldx

Hello there,

I've searched far and wide and even https://github.com/hubotio/hubot/issues/396#issuecomment-455020900 on an old hopefully-related issue but no 🎲 🎲.

Basically I feel like hubot's help system could be waaaaaaaay better. More specifically, it could be better than an [alphabetically sorted](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L515) parsing of [comments that are "documentation sections"](https://github.com/hubotio/hubot/blob/3e32c1e380ca9ce39a7c25a4d277c24de6c70c7a/src/robot.js#L544).

I was about to begin working on it when I thought I'd open an issue here -- anyone do anything else?

Or maybe the current help system is enough? That is, maybe I'm doing something wrong?

**Comment by joeyguerra** [comment]
fixed by https://github.com/hubotio/hubot/pull/1585

**Comment by arigoldx** [comment]
say @joeyguerra not that i mind one way or another but out of curiosity:

how does a PR that removes trailing spaces fix the organization of the help system?

was it a case where the trailing spaces messed up sorting or something?

**Comment by joeyguerra** [comment]
That's an excellent question :) I made a mistake linking that PR to this issue.

Btw, we've rebooted Hubot development at the original org/repo. The issue you created is still opened over there: https://github.com/hubotio/hubot/issues/1490

**Comment by arigoldx** [comment]
all good.. was kinda hoping it'd be a cool edge case i was unaware of 😎
