### ISSUE TITLE
Test is pending, blocking `npm test` from exiting

### ISSUE THREAD

**Issue by joeyguerra** [hubot-new/hubot#33]
When running tests locally via `npm test`, the process fails to exit.

I'm running MacOS, Node version v16.19.0.

**Comment by xurizaemon** [comment]
Shows up in CI also: https://github.com/hubot-new/hubot/actions/runs/4633376282/jobs/8198532499?pr=30#step:5:341

**Comment by joeyguerra** [comment]
Can we try Node v19? That's what I'm running locally.

**Comment by xurizaemon** [comment]
Added v latest (currently Node v19 right?) to the test matrix in #30.

That IMO is nicer than specifying because it will give us early warning if things break on a new latest version, and we can add LTS versions more manually.
